name = "aggie-guide"
type = "webpack"
route = ''
zone_id = ''
usage_model = ''
compatibility_flags = []
workers_dev = true
compatibility_date = "2024-01-20"

account_id = "313e49c64a9bdfb07ca4198896784cbb" 

# Define your KV namespace binding
kv_namespaces = [
  { binding = "AGGIE_ACCOUNTS", id = "33693a68666a4289baceb4de378fa7f3" }
]

